#!/bin/bash

pacman -S zsh python-pip pulseaudio pulseaudio-alsa pavucontrol ttf-font-awesome base-devel python-pywal sway wofi vim neovim dhcpcd networkmanager grub efibootmgr waybar kitty xorg-server-common xorg-server-xwayland chromium mako wl-clipboard swaylock swayidle slurp grim pamixer light

ln -sf /usr/share/zoneinfo/Europe/London /etc/localtime

hwclock --systohc

echo Time to configure locales, press enter to continue
read
vim /etc/locale.gen

locale-gen

echo LANG=en_GB.UTF-8 >> /etc/locale.conf

echo KEYMAP=uk >> /etc/vconsole.conf

echo Enter a computer hostname to use
read hostname

echo $hostname >> /etc/hostname

echo -e "127.0.0.1  localhost\n::1 localhost\n127.0.0.1   $hostname.localdomain $hostname" >> /etc/hosts

systemctl enable dhcpcd
systemctl enable NetworkManager

grub-install --target=x86_64-efi --efi-directory=/boot --bootloader-id=GRUB

grub-mkconfig -o /boot/grub/grub.cfg

echo Set root password:
passwd

echo Enter username for main account
read username
useradd -m $username

echo set password for main account
passwd techtino

gpasswd -a $username wheel

echo '%wheel ALL=(ALL) NOPASSWD: ALL' | sudo EDITOR='tee -a' visudo

echo Installing zsh, setting as default shell and installing oh-my-zsh
su $username -c 'sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"'

su $username -c 'git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting'
su $username -c 'git clone https://github.com/zsh-users/zsh-autosuggestions.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions'

echo Downloading and copying dotfiles
cd /home/$username
git clone https://github.com/techtino/Homedir-desktop
cp -r Homedir-desktop/. .
git clone https://aur.archlinux.org/yay-git.git

chown -R $username:$username .
cd yay-git
su $username -c 'makepkg -si'
cd /home/$username
pip3 install wpgtk
mkdir -p /home/$username/.config/wpg/templates
chown -R $username:$username .
su $username -c 'wpg-install.sh -g'
su $username -c 'wpg-install.sh -i'

git clone https://gitlab.com/bit9tream/bitfetch.git
cd bitfetch
make CC=gcc bitfetch XINERAMA=NO X=NO
make install

su $username -c 'yay -S breeze-default-cursor-theme'
su $username -c 'yay -S clipman'
su $username -c 'yay -S wob'
su $username -c 'yay -S autotiling'
su $username -c 'yay -S redshift-wayland-git'
su $username -c 'yay -S libinput-gestures'
su $username -c 'yay -S swappy'


echo Setting up touchpad gestures

gpasswd -a $username input

echo -e '#!/bin/sh\ncase "$@" in\nforward )\nswaymsg seat seat0 cursor press BTN_EXTRA\nswaymsg seat seat0 cursor release BTN_EXTRA\n;;\nbackward )\nswaymsg seat seat0 cursor press BTN_SIDE\nswaymsg seat seat0 cursor release BTN_SIDE\n;;\nesac' >> /usr/local/bin/button

chmod +x /usr/local/bin/button

rm /etc/libinput-gestures.conf
echo -e "gesture swipe up swaymsg -t command workspace next_on_output\ngesture swipe down swaymsg -t command workspace prev_on_output\ngesture swipe right /usr/local/bin/button backward\ngesture swipe left /usr/local/bin/button forward" >> /etc/libinput-gestures.conf

echo Setting logind ignore power key

echo "HandlePowerKey=ignore" >> /etc/systemd/logind.conf

echo Its time to reboot, done here.
read
