#!/bin/bash

pacman -S pulseaudio pulseaudio-alsa pavucontrol ttf-font-awesome base-devel python-pywal sway wofi vim neovim sudo dhcpcd networkmanager grub efibootmgr waybar kitty xorg-server-common xorg-server-xwayland chromium

ln -sf /usr/share/zoneinfo/Europe/London /etc/localtime

hwclock --systohc

echo Time to configure locales, press enter to continue
read
vim /etc/locale.gen

locale-gen

echo LANG=en_GB.UTF-8 >> /etc/locale.conf

echo KEYMAP=uk >> /etc/vconsole.conf

echo Enter a computer hostname to use
read hostname

echo $hostname >> /etc/hostname

echo -e "127.0.0.1  localhost\n::1 localhost\n127.0.0.1   $hostname.localdomain $hostname" >> /etc/hosts

systemctl enable dhcpcd
systemctl enable NetworkManager

grub-install --target=x86_64-efi --efi-directory=/boot --bootloader-id=GRUB

grub-mkconfig -o /boot/grub/grub.cfg

echo Set root password:
passwd

echo Enter username for main account
read username
useradd -m $username

echo set password for main account
passwd techtino

gpasswd -a $username wheel

echo Time to edit sudoers file, uncomment wheel line
read
visudo

echo Installing zsh, setting as default shell and installing oh-my-zsh
pacman -S zsh
su $username -c 'sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"'

echo Downloading and copying dotfiles
cd /home/$username
git clone https://github.com/techtino/Homedir-desktop
cp -r Homedir-desktop/. .

git clone https://aur.archlinux.org/yay-git

chown -R $username:$username .

echo Its time to reboot, done here. All thats left is to install yay, wpgtk-git and bitfetch!
read
